application: wefunk-api
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /admin/.*
  script: app.py
  login: admin
- url: .*
  script: app.py
